[General]
OmegaMultiplier=2
IndustryOmegaCapacityMultiplier=0.2

[Controls]

[DensityProfiles]
VeryLowCapacity=5000
LowCapacity=10000
MediumCapacity=60000
HighCapacity=100000
VeryLowEmptyingRate=0.35
LowEmptyingRate=0.8
MediumEmptyingRate=2.25
HighEmptyingRate=4

[Markers]
MarkerRadius=0.5
MarkerHeight=1

###############
Office
###############

[MainOffice]
Name=Logistic Office
Coordinates=-333.33,-2778.94,5.15

[VehicleSpawn]
Name=Vehicle Spawn
Coordinates=-360.04,-2763.21,6

###############
Industries
###############

[OreMine]
Name=Ore Loading Area
Coordinates=2623,2784,33.70
OreProductionRate=
Inputs=Omega
Outputs=Ore
IndustryInputCapacity=100000
IndustryOutputCapacity=100000

[CoalMine]
Name=Coal Loading Area
Coordinates=2948,2747,43
CoalProductionRate=
Inputs=Omega
Outputs=Coal
IndustryInputCapacity=100000
IndustryOutputCapacity=100000

[OilField]
Name=Grand Senora Desert
Coordinates=587,2936,41
OilProductionRate=
Inputs=Omega
Outputs=Oil
IndustryInputCapacity=100000
IndustryOutputCapacity=100000

[OilField2]
Name=El Burro Heights
Coordinates=1718,-1645,112.5
OilProductionRate=
Inputs=Omega
Outputs=Oil
IndustryInputCapacity=100000
IndustryOutputCapacity=100000

[Refinery]
Name=Palmer-Taylor Refinery
Coordinates=2766,1472,24.5
Inputs=Oil,Omega
Outputs=Plastic,Fuel
IndustryInputCapacity=100000
IndustryOutputCapacity=50000

[SmeltingFactory]
Name=Cypress Flats Smelting Factory
Coordinates=985,-1922,31.1
Inputs=Ore,Omega,Coal
Outputs=Metal,Alloy,Recyclable
IndustryInputCapacity=100000
IndustryOutputCapacity=50000

[ProcessorFactory]
Name=Cypress Flats Processor Factory
Coordinates=938,-2544,28.3
Inputs=Plastic,Alloy,Omega
Outputs=Electronic,Recyclable
IndustryInputCapacity=20000
IndustryOutputCapacity=10000

[ConsumerElectronicsFactory]
Name=Consumer Electronics Factory
Coordinates=-1152,-2183,13.20
Inputs=Electronic,Omega
Outputs=TV,Computer,Recyclable
IndustryInputCapacity=10000
IndustryOutputCapacity=5000

[RecyclingCenter]
Name=La Puerta Recycling Center
Coordinates=-596,-1586,26.75
Inputs=Recyclable
Outputs=Metal,Alloy,Plastic
IndustryInputCapacity=50000
IndustryOutputCapacity=25000

[OmegaFactory]
Name=Rancho Omega Factory
Coordinates=494,-1969,24.92
Inputs=Oil,Ore
Outputs=Omega
IndustryInputCapacity=100000
IndustryOutputCapacity=10000

[CoalStorage]
Name=Elysian Island
Coordinates=622,-2770,6
Inputs=Coal
Outputs=Coal
IndustryInputCapacity=1000000
IndustryOutputCapacity=1000000

###############
Store
###############

[Store1]
Name=Davis Carson Store
Coordinates=103,-1818,26.53
Inputs=TV,Computer
Outputs=None
IndustryInputCapacity=100000

[Store2]
Name=Burton Mall
Coordinates=-250,-250,36.52
Inputs=TV,Computer
Outputs=None
IndustryInputCapacity=100000

[Store3]
Name=Sandy Shore Carson Store
Coordinates=2673,3520,52.71
Inputs=TV,Computer
Outputs=None
IndustryInputCapacity=100000

[Store4]
Name=Grapeseed Store
Coordinates=1718,4805,41.71
Inputs=TV,Computer
Outputs=None
IndustryInputCapacity=10000

[Store5]
Name=Paleto Store
Coordinates=-361,6065,31.50
Inputs=TV,Computer
Outputs=None
IndustryInputCapacity=10000

[HarborTerminal]
Name=Terminal
Coordinates=1244,-3142,5.5
Inputs=Coal,Omega,Ore,Plastic,Fuel,Electronic,TV,Computer,Metal,Alloy
Outputs=None
IndustryInputCapacity=100000

###############
Petrol Stations
###############

[Petrol Station 01]
Enabled=true
Name=Davis Ave
Company=LTD
Coordinates=-66,-1759,29
Density=medium
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 02]
Enabled=true
Name=El Rancho Blvd
Company=RON
Coordinates=1209,-1402,35
Density=high
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 03]
Enabled=true
Name=Popular St
Company=RON
Coordinates=831,-1028,26
Density=high
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 04]
Enabled=true
Name=Capital Blvd
Company=XERO
Coordinates=254,-1263,29
Density=medium
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 05]
Enabled=true
Name=Calais Ave
Company=XERO
Coordinates=-522,-1204,18
Density=medium
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 06]
Enabled=true
Name=Ginger St
Company=LTD
Coordinates=-713,-935,19
Density=high
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 07]
Enabled=true
Name=US Route 15
Company=RON
Coordinates=2591,361,108
Density=medium
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 08]
Enabled=true
Name=Mirror Park Blvd
Company=LTD
Coordinates=1178,-319,69
Density=low
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 09]
Enabled=true
Name=Clinton Ave
Company=Globe Oil
Coordinates=634,270,103
Density=high
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 10]
Enabled=true
Name=Rockford Dr
Company=RON
Coordinates=-1432,-272,46
Density=high
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 11]
Enabled=true
Name=Interstate 2
Company=XERO
Coordinates=-2085,-322,13
Density=high
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 12]
Enabled=true
Name=Rockford Dr
Company=LTD
Coordinates=-1792,814,138
Density=low
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 13]
Enabled=true
Name=US Route 68
Company=RON
Coordinates=-2556,2346,33
Density=medium
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 14]
Enabled=true
Name=US Route 68
Company=XERO
Coordinates=48,2776,57
Density=very low
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 15]
Enabled=true
Name=Senora Rd
Company=Globe Oil
Coordinates=264,2610,44
Density=very low
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 16]
Enabled=true
Name=US Route 68
Company=Globe Oil
Coordinates=1207,2658,37
Density=low
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 17]
Enabled=true
Name=US Route 13
Company=XERO
Coordinates=2682,3261,55.24
Density=medium
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 18]
Enabled=true
Name=Marina Dr
Company=XERO
Coordinates=2006,3772,32
Density=low
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 19]
Enabled=true
Name=Main St
Company=LTD
Coordinates=1689,4930,42
Density=low
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 20]
Enabled=true
Name=US Route 13
Company=Globe Oil
Coordinates=1700,6415,32
Density=medium
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 21]
Enabled=true
Name=US Route 1
Company=RON
Coordinates=195,6607,31
Density=medium
StartingTank=0.3
Inputs=Fuel
Outputs=None

[Petrol Station 22]
Enabled=true
Name=Cascabel Ave
Company=XERO
Coordinates=-94,6424,31
Density=low
StartingTank=0.3
Inputs=Fuel
Outputs=None

###############
Vehicles
###############

[LightCommercialTruck]
Enabled=true
ModelName=mule,mule2,mule3,mule4,mule5
VehicleCapacity=10000
VehicleCargoType=Crate

[MediumCommercialTruck]
Enabled=true
ModelName=pounder,pounder2
VehicleCapacity=20000
VehicleCargoType=Crate

[LooseTrucks]
Enabled=true
ModelName=tiptruck,tiptruck2
VehicleCapacity=10000
VehicleCargoType=Loose

[CrateTrailers]
Enabled=true
ModelName=trailers,trailer3,trailers4
VehicleCapacity=30000
VehicleCargoType=Crate

[FluidTrailers]
Enabled=true
ModelName=tanker,tanker2
VehicleCapacity=30000
VehicleCargoType=Fluid

[SolidTrailers]
Enabled=true
ModelName=trflat
VehicleCapacity=30000
VehicleCargoType=Solid

[Trucks]
Enabled=true
ModelName=hauler,hauler2,packer,phantom,phantom3,phantom4
VehicleCapacity=0
VehicleCargoType=Trailer

###############
Objects
###############

Box=prop_boxpile_05a
TVBox=ex_prop_crate_elec_sc
