[General]
OmegaMultiplier=2
IndustryOmegaCapacityMultiplier=0.2
IndustryOwnerCut=0.5

[Controls]
OpenModMenu=F7
GateInteract=E

[GasStationDensityProfiles]
VeryLowCapacity=5000
LowCapacity=10000
MediumCapacity=60000
HighCapacity=100000
VeryLowEmptyingRate=0.35
LowEmptyingRate=0.8
MediumEmptyingRate=2.25
HighEmptyingRate=4

[StoreDensityProfiles]
VeryLowCapacity=5000
LowCapacity=10000
MediumCapacity=60000
HighCapacity=100000
VeryLowEmptyingRate=0.35
LowEmptyingRate=0.8
MediumEmptyingRate=2.25
HighEmptyingRate=4

[Markers]
MarkerRadius=0.5
MarkerHeight=1

###############
Office
###############

[MainOffice]
Name=Logistic Office
Coordinates=-115.15,-2517,6

[VehicleSpawn]
Name=Vehicle Spawn
Coordinates=-97.75,-2498.41,6
VehicleSpawnHeading=234

###############
Industries
###############

[MineralMine]
Name=Quarry
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[OilField]
Name=Grand Senora Desert Oil Field
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[Refinery]
Name=El Burro Heights Refinery
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[PlasticFactory]
Name=Los Santos Plastic Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[SmeltingFactory]
Name=Cypress Flats Smelting Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[MechanicalPartsFactory]
Name=La Mesa Mechanical Parts Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[ProcessorFactory]
Name=Cypress Flats Processor Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[ConsumerElectronicsFactory]
Name=Consumer Electronics Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[RecyclingCenter]
Name=La Puerta Recycling Center
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[OmegaFactory]
Name=Rancho Omega Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[Forest]
Name=Paleto Forest
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[Sawmill]
Name=Paleto Bay Sawmill
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[WoodFurnitureFactory]
Name=Cypress Flats Wood Furniture Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[Farm]
Name=Grapeseed Farm
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[AlcoholFactory]
Name=La Mesa Alcohol Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[Slaughterhouse]
Name=Elysian Island Slaughterhouse
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[FoodProcessingFactory]
Name=CluckingBell Food Processing Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[FabricFactory]
Name=La Mesa Fabric Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[ClothingFactory]
Name=La Mesa Clothing Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[ChemicalPlant]
Name=Palmer-Taylor Chemical Plant
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[PharmaceuticalFactory]
Name=Humane Labs Pharmaceutical Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[CementFactory]
Name=Grand Senora Cement Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[ConcreteFactory]
Name=Elysian Island Concrete Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[BricksFactory]
Name=Grand Senora Bricks Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[BeamFactory]
Name=Cypress Flats Beam Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

[VehicleFactory]
Name=Los Santos Vehicle Factory
IndustryInputCapacity=100000
IndustryOutputCapacity=100000
IndustryPrice=1000000
IndustryLicencePrice=50000
IndustryProductionRate=60

###############
Store
###############

[Store1]
Name=Davis Carson Store
StoreInputCapacity=100000

[Store2]
Name=Burton Mall
StoreInputCapacity=100000

[Store3]
Name=Sandy Shores Carson Store
StoreInputCapacity=100000

[Store4]
Name=Grapeseed Store
StoreInputCapacity=10000

[Store5]
Name=Paleto Store
StoreInputCapacity=10000

[HarborTerminal]
Name=Terminal
StoreInputCapacity=100000

###############
Petrol Stations
###############

[Petrol Station 01]
Enabled=true
Name=Davis Ave
Company=LTD
Density=medium
StartingTank=0.3

[Petrol Station 02]
Enabled=true
Name=El Rancho Blvd
Company=RON
Density=high
StartingTank=0.3

[Petrol Station 03]
Enabled=true
Name=Popular St
Company=RON
Density=high
StartingTank=0.3

[Petrol Station 04]
Enabled=true
Name=Capital Blvd
Company=XERO
Density=medium
StartingTank=0.3

[Petrol Station 05]
Enabled=true
Name=Calais Ave
Company=XERO
Density=medium
StartingTank=0.3

[Petrol Station 06]
Enabled=true
Name=Ginger St
Company=LTD
Density=high
StartingTank=0.3

[Petrol Station 07]
Enabled=true
Name=US Route 15
Company=RON
Density=medium
StartingTank=0.3

[Petrol Station 08]
Enabled=true
Name=Mirror Park Blvd
Company=LTD
Density=low
StartingTank=0.3

[Petrol Station 09]
Enabled=true
Name=Clinton Ave
Company=Globe Oil
Density=high
StartingTank=0.3

[Petrol Station 10]
Enabled=true
Name=Morningwood
Company=RON
Density=high
StartingTank=0.3

[Petrol Station 11]
Enabled=true
Name=Interstate 2
Company=XERO
Density=high
StartingTank=0.3

[Petrol Station 12]
Enabled=true
Name=Rockford Dr
Company=LTD
Density=low
StartingTank=0.3

[Petrol Station 13]
Enabled=true
Name=US Route 68 - Zancudo
Company=RON
Density=medium
StartingTank=0.3

[Petrol Station 14]
Enabled=true
Name=US Route 68 - Grand Senora Desert - East
Company=XERO
Density=very low
StartingTank=0.3

[Petrol Station 15]
Enabled=true
Name=Senora Rd
Company=Globe Oil
Density=very low
StartingTank=0.3

[Petrol Station 16]
Enabled=true
Name=US Route 68 - Grand Senora Desert - West
Company=Globe Oil
Density=low
StartingTank=0.3

[Petrol Station 17]
Enabled=true
Name=US Route 13
Company=XERO
Density=medium
StartingTank=0.3

[Petrol Station 18]
Enabled=true
Name=Sandy Shores Marina Drive
Company=XERO
Density=low
StartingTank=0.3

[Petrol Station 19]
Enabled=true
Name=Grapeseed Main Street
Company=LTD
Density=low
StartingTank=0.3

[Petrol Station 20]
Enabled=true
Name=US Route 13 - Mount Chiliad
Company=Globe Oil
Density=medium
StartingTank=0.3

[Petrol Station 21]
Enabled=true
Name=US Route 1
Company=RON
Density=medium
StartingTank=0.3

[Petrol Station 22]
Enabled=true
Name=Cascabel Ave
Company=XERO
Density=low
StartingTank=0.3

###############
Vehicles
###############

[CommercialVans]
ModelName=burrito3,burrito4,pony,pony2,rumpo,rumpo2,speedo,speedo4,speedo5
VehicleCapacity=3000
VehicleCargoType=CraftedGoods

[CommercialBigVans]
ModelName=boxville,boxville2,boxville3
VehicleCapacity=5000
VehicleCargoType=CraftedGoods

[LightCommercialTruck]
ModelName=mule,mule2,mule3,mule4,mule5
VehicleCapacity=10000
VehicleCargoType=CraftedGoods

[MediumCommercialTruck]
ModelName=pounder,pounder2
VehicleCapacity=20000
VehicleCargoType=CraftedGoods

[AggregateTrucks]
ModelName=tiptruck,tiptruck2
VehicleCapacity=20000
VehicleCargoType=Aggregates

[CraftedGoodsTrailers]
ModelName=trailers,trailer3,trailers4
VehicleCapacity=30000
VehicleCargoType=CraftedGoods

[LiquidTrailers]
ModelName=tanker,tanker2
VehicleCapacity=30000
VehicleCargoType=Liquid

[OpenHullTrailers]
ModelName=trflat
VehicleCapacity=30000
VehicleCargoType=OpenHull

[Trucks]
ModelName=hauler,hauler2,packer,phantom,phantom3,phantom4
VehicleCapacity=0
VehicleCargoType=Trailer

[DryBulkTrucks]
ModelName=mixer,mixer2
VehicleCapacity=10000
VehicleCargoType=DryBulk

[RefrigeratedTrailers]
ModelName=trailers2
VehicleCapacity=30000
VehicleCargoType=Refrigeration

[RecyclableTrucks]
ModelName=biff,rubble
VehicleCapacity=20000
VehicleCargoType=Recyclable

[VehicleTrailers]
ModelName=tr2
VehicleCapacity=4
VehicleCargoType=Vehicles

[WoodTrailer]
ModelName=trailerlogs
VehicleCapacity=30000
VehicleCargoType=Trailer